## read_csv pandas doc link : https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

# 1. importing pandas

In [1]:
import pandas as pd

# 2. Opening a local csv file

In [7]:
df= pd.read_csv('aug_train.csv')

# db present in same folder hence we just write the name otherwise we use relative path of the file to access it through read_csv function

In [18]:
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

# 3. opening a csv file from a url

## <font color='red'> We can use the following code to get data of csv file from any server.</font>
We're using requests module.
Here our program act as a user/client and request the data. This request is sent with the header defined in "headers" below.
we fetch all the data of file from a url using requests.get() and store it in req variable.

In [29]:
import requests
from io import StringIO
import pandas as pd

url = "https://raw.githubusercontent.com/datasets/covid-19/master/data/countries-aggregated.csv"
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

              Date      Country  Confirmed  Recovered  Deaths
0       2020-01-22  Afghanistan          0          0       0
1       2020-01-23  Afghanistan          0          0       0
2       2020-01-24  Afghanistan          0          0       0
3       2020-01-25  Afghanistan          0          0       0
4       2020-01-26  Afghanistan          0          0       0
...            ...          ...        ...        ...     ...
161563  2022-04-12     Zimbabwe     247094          0    5460
161564  2022-04-13     Zimbabwe     247160          0    5460
161565  2022-04-14     Zimbabwe     247208          0    5462
161566  2022-04-15     Zimbabwe     247237          0    5462
161567  2022-04-16     Zimbabwe     247237          0    5462

[161568 rows x 5 columns]

## <font color='red'>To load the CSV file from GitHub directly into a Pandas DataFrame.</font>

In [25]:
import requests
from io import StringIO
url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

df = pd.read_csv(data)
print(df.head())

    Country  Region
0   Algeria  AFRICA
1    Angola  AFRICA
2     Benin  AFRICA
3  Botswana  AFRICA
4   Burkina  AFRICA

# Steps to Get the Raw CSV Link from a github repo

1. Go to the repository on GitHub where the .csv file is located.

    Example: https://github.com/cs109/2014_data

2. Navigate inside the repo until you see the .csv file (e.g., olympicAthletes.csv).

3. Click on the file name → GitHub will open a preview of the CSV.

4. At the top-right, you’ll see a button “Raw”.

5. Click it → it opens the file in raw text format.

6. Copy the URL from your browser.
    Here url will look like this : https://github.com/cs109/2014_data/blob/master/olympicAthletes.csv

8.Now, Replace github.com → raw.githubusercontent.com and Remove the word blob/ from the path

   here url for raw csv: https://raw.githubusercontent.com/cs109/2014_data/master/olympicAthletes.csv

In [59]:
import requests
from io import StringIO
url = "https://raw.githubusercontent.com/thewiremonkey/factbook.csv/master/categories.csv"
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

     Num            Category                    Name
0   2147           Geography                    Area
1   2119  People and Society              Population
2   2002  People and Society  Population growth rate
3   2054  People and Society              Birth rate
4   2066  People and Society              Death rate
..   ...                 ...                     ...
69  2121      Transportation                Railways
70  2085      Transportation                Roadways
71  2093      Transportation               Waterways
72  2108      Transportation         Merchant marine
73  2034            Military   Military expenditures

[74 rows x 3 columns]

# 4. Sep parameter
read_csv() func take comma as separater by default, so to read tsv files properly we can define sep = '/t'.
Some dataset does not contain separate row for column names and the first row become row of column names. we can create these column names via 'names' parameter.

In [70]:
pd.read_csv('movie_titles_metadata.tsv', sep='\t', names=['sno.','name', 'release year', 'rating', 'votes', 'genres'] )

,sno.,name,release year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

## 5. Index_col parameter

In [80]:
pd.read_csv('aug_train.csv',index_col = 'enrollee_id')

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

## 6. Header parameter
Sometimes in database 1st row is the column header but pandas is unable to identify it. so we use "header = 1" to make our first row as column name or header.

Here in our example database has column names defined correctly we have just take an example to make our first row as column name

In [132]:
pd.read_csv("aug_test.csv", header=1)

,32403,city_41,0.8270000000000001,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,Unnamed: 10,1,21
0,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
1,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
2,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
3,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
4,217,city_23,0.899,Male,No relevent experience,Part time course,Masters,STEM,10,NaN,NaN,2,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2123,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15
2124,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
2125,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18
2126,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84
2127,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11

## 7. use_cols parameter
Read/import selected columns of a csv file

In [87]:
pd.read_csv("aug_train.csv", usecols = ['enrollee_id','city','gender','education_level'])

       enrollee_id      city gender education_level
0             8949  city_103   Male        Graduate
1            29725   city_40   Male        Graduate
2            11561   city_21    NaN        Graduate
3            33241  city_115    NaN        Graduate
4              666  city_162   Male         Masters
...            ...       ...    ...             ...
19153         7386  city_173   Male        Graduate
19154        31398  city_103   Male        Graduate
19155        24576  city_103   Male        Graduate
19156         5756   city_65   Male     High School
19157        23834   city_67    NaN  Primary School

[19158 rows x 4 columns]

## 8. How to Read a Single Column as a Series
Import file as pandas series instead of dataframeies'>

In [119]:
## Method 1: Use squeeze explicitly on the DataFrame
gender_series = pd.read_csv("aug_train.csv", usecols=["gender"]).squeeze("columns")
gender_series

0        Male
1        Male
2         NaN
3         NaN
4        Male
         ...
19153    Male
19154    Male
19155    Male
19156    Male
19157     NaN
Name: gender, Length: 19158, dtype: object

In [123]:
## Method 2: Directly select the column
gender_series = pd.read_csv("aug_train.csv", usecols=["gender"])["gender"]
print(type(gender_series))  # <class 'pandas.Series'>
gender_series

<class 'pandas.core.series.Series'>

0        Male
1        Male
2         NaN
3         NaN
4        Male
         ...
19153    Male
19154    Male
19155    Male
19156    Male
19157     NaN
Name: gender, Length: 19158, dtype: object

In [127]:
df = pd.read_csv("aug_train.csv", usecols=["city"])
gender_series = df.squeeze("columns")
print(type(df))  # <class 'pandas.Series'>
df
df.value_counts

<class 'pandas.core.frame.DataFrame'>

<bound method DataFrame.value_counts of            city
0      city_103
1       city_40
2       city_21
3      city_115
4      city_162
...         ...
19153  city_173
19154  city_103
19155  city_103
19156   city_65
19157   city_67

[19158 rows x 1 columns]>

In [116]:
pd.read_csv("aug_train.csv", usecols=["city"])["city"].value_counts()

city
city_103    4355
city_21     2702
city_16     1533
city_114    1336
city_160     845
            ...
city_129       3
city_111       3
city_121       3
city_140       1
city_171       1
Name: count, Length: 123, dtype: int64

## 9. Skiprows/nrows Parameter

In [5]:
pd.read_csv("aug_train.csv", skiprows = [0,9], nrows= 10)

,8949,city_103,0.92,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,Unnamed: 9,Unnamed: 10,1,36,1.0
0,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
1,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
2,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
3,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
4,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
5,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
6,402,city_46,0.762,Male,Has relevent experience,no_enrollment,Graduate,STEM,13,<10,Pvt Ltd,>4,18,1.0
7,699,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,17,10000+,Pvt Ltd,>4,123,0.0
8,29452,city_21,0.624,NaN,No relevent experience,Full time course,High School,NaN,2,NaN,NaN,never,32,1.0
9,23853,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,5,5000-9999,Pvt Ltd,1,108,0.0

In [149]:
df = pd.read_csv("aug_train.csv", skiprows=lambda x: x % 2 == 0)
# skip all even-numbered rows
df

,8949,city_103,0.92,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,Unnamed: 9,Unnamed: 10,1,36,1.0
0,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
1,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
2,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
3,27107,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,7,50-99,Pvt Ltd,1,46,1.0
4,29452,city_21,0.624,NaN,No relevent experience,Full time course,High School,NaN,2,NaN,NaN,never,32,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9573,9212,city_21,0.624,NaN,Has relevent experience,no_enrollment,Masters,STEM,3,100-500,Pvt Ltd,3,40,1.0
9574,32313,city_160,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,10,100-500,Public Sector,3,23,0.0
9575,29754,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,Humanities,7,10/49,Funded Startup,1,25,0.0
9576,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
9577,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0

## 10. Encoding parameter
Used to resolve UnicodeDecodeError. If we know the encoding we can pass it in the parameter otherwise we can edit the encoding of database in code editor.

In [18]:
pd.read_csv('zomato.csv',encoding = 'latin-1', nrows=3)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270

## 11. Skip bad lines

In [32]:
import requests
from io import StringIO
import pandas as pd

url = "https://raw.githubusercontent.com/cs109/2014_data/master/olympicAthletes.csv"

headers = {"User-Agent": "Mozilla/5.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

df = pd.read_csv(data,sep='\t',names=['id','athelete name','gender','age','sport'],index_col='id',skiprows=1, on_bad_lines="skip")   # skips problematic rows
print(df.head())

         athelete name gender  age      sport
id
0      Rohullah Nikpai   Male   25  Taekwondo
1         Masoud Azizi   Male   27  Athletics
2   Nesar Ahmad Bahawi   Male   28  Taekwondo
3         Ajmal Faisal   Male   21     Boxing
4       Ajmal Faizzada   Male   25       Judo

In [56]:
df= pd.read_csv('BX_Books.csv', sep=';', encoding="latin-1", on_bad_lines='skip', nrows=3)
df

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,2005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,60973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...

## 12. dtypes parameter

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ISBN                 3 non-null      int64
 1   Book-Title           3 non-null      object
 2   Book-Author          3 non-null      object
 3   Year-Of-Publication  3 non-null      int64
 4   Publisher            3 non-null      object
 5   Image-URL-S          3 non-null      object
 6   Image-URL-M          3 non-null      object
 7   Image-URL-L          3 non-null      object
dtypes: int64(2), object(6)
memory usage: 324.0+ bytes

In [78]:
pd.read_csv('aug_train.csv').info() 
# Target is float is of dtype can be defined as int to save memory.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [76]:
df = pd.read_csv('aug_train.csv',dtype = {'target':int})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int32
dtypes: float64(1), int32(1), int64(2), object(10)
memory usage: 2.0+ MB

## 13. Handling dates
Most of the times the date column is passed as string in databases and we cannot perform datetime operations on them, So we parse the date column so we can use it's functionalities properly.

In [108]:
pd.read_csv('IPL Matches 2008-2020.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [111]:
df = pd.read_csv('IPL Matches 2008-2020.csv', parse_dates=['date'])
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

## 14. Converters

In [115]:
# Function definition used for converters/transformation of column.
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name

# Calling the function
rename("Royal Challengers Bangalore")

# Using the function as a converter
pd.read_csv('IPL Matches 2008-2020.csv', converters={'team1':rename}).head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

## 15. na_value parameter
Sometimes the NaN values are not very direct, they are in forms of hiphen (-) or something else. In these cases we can specify the kind of values we are considering NaN

In [124]:
pd.read_csv('aug_train.csv',na_values = ['no_enrollment', 'never']).head()
# in 'enrolled_university' column all the values 'no_enrollment' are converted to NaN. Similarly in 'last_new_job' column all the 'never' values are converted to NaN

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,NaN,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,NaN,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,NaN,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,NaN,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,NaN,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

# 16. Loading huge datsets in chunks
Used when dataset size is very large. In these situation we can load the database in chunks and apply condinals to process/loop it.

In [126]:
dfs = pd.read_csv('aug_train.csv', chunksize=5000)

for chunk in dfs:
    print(chunk.shape)

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)